#!/usr/bin/python
#
# czexpressvpn - graphical interface for ExpressVPN
#
# Copyright 2017 Alexander Czutro
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# INSTALLING
#
# Copy file `czexpressvpn` to any directory in your $PATH variable.  If
# necessary, make the file executable (`chmod +x /chosen/path/czexpressvpn`).
#
# ExpressVPN needs to be installed separately following the instructions
# provided by the vendor.
#
###############################################################################

from subprocess import Popen as _child, PIPE as _pipe;

import pygtk;
pygtk.require('2.0');
import gtk;
import gobject;
import re


### constants #################################################################

_EXPRESSVPN = 'expressvpn';


### help functions ############################################################

def call(*args):
    '''
    Runs a non-interactive sub-process and returns its outputs and
    exit code.
    '''
    P = _child(args, stdin=None, stdout=_pipe, stderr=_pipe);
    stdout, stderr = P.communicate();
    return P.returncode, stdout, stderr;
#call


### tray-based hub ############################################################

class Trayhub:
    '''Main application class around a "system tray" icon.'''

    ### class constructor #########################################

    def __init__(self):
        self.status = None; # string: None or location name
        self.locations = [];
        self.cursleep = gobject.timeout_add_seconds(60, self.forever_loop);

        self.status_icon = gtk.StatusIcon();
        self.icon_menu_connection = self.status_icon.connect(
            'button-press-event', self.show_menu
        );
        self.menu = gtk.Menu();
        self.submenu = gtk.Menu();

        self.update_all();

        return;
    #__init__

    ### back-end functions ########################################

    def get_status(self):
        '''Updates self.status according to expressvpn status call.'''
        retcode, stdout, stderr = call(_EXPRESSVPN, 'status');
        if retcode != 0:
            return; # if call failed, do nothing

        # Keep only first line of output, and remove formatting
        # (color, boldness)
        first_line = stdout.split('\n')[0]
        to_remove = re.compile(r'\x1B\[[0-?]*[ -/]*[@-~]')
        output_unformatted = to_remove.sub('', first_line)

        output_array = output_unformatted.replace('\n', '').split(' ');
        first_two = ''.join(output_array[0:2]);

        if first_two == 'Notconnected.':
            self.status = None;
        elif first_two == 'Connectedto':
            self.status = ' '.join(output_array[2:]);
        else:
            print('possible bug; expressvpn returned:\n', stdout, stderr);
        return;


    def get_locations(self, argument):
        '''
        Updates self.locations to contain the locations requested in
        'argument'. (See documentation for 'expressvpn list'.)
        '''
        command_line = [_EXPRESSVPN, 'list'];
        if argument is not None:
            command_line.append(argument);
        #if
        retcode, stdout, stderr = call(*command_line);
        if retcode != 0:
            message = gtk.MessageDialog(
                parent=None,
                flags=0,
                type=gtk.MESSAGE_ERROR,
                buttons=gtk.BUTTONS_CLOSE,
                message_format=("expressvpn list failed:\n%s" % stderr)
            );
            message.run();
            message.destroy();
        else:
            output_lines = stdout.split('\n');
            output_matrix = [];
            for line in output_lines:
                output_matrix.append(line.split('\t'));
            #for
            self.locations = [];
            if argument == 'recent':
                distilled_matrix = [
                    [token for token in row if token]
                    for row in output_matrix
                ];
                for row in distilled_matrix:
                    if row and row[0] not in ['ALIAS', '-----', '']:
                        self.locations.append([row[0], row[-2]]);
                    #if
                #for
            elif argument == 'recommended':
                for row in output_matrix:
                    if row and row[0] not in ['ALIAS', '-----', '']:
                        self.locations.append([row[0], row[-1]]);
                    #if
                #for
            else:
                distilled_matrix = [[token for token in row
                                     if token not in ['', 'Y']]
                                    for row in output_matrix
                ];
                for row in distilled_matrix:
                    if row and row not in ['ALIAS', '-----', '']:
                        self.locations.append([row[0], row[-1]]);
                    #if
                #for
            #else
        return;
    #get_locations


    def do_list(self, widget, argument):
        '''
        Opens a popup menu offering to connect to a list of locations.
        'argument': see documentation for 'expressvpn list'.
        '''
        self.get_locations(argument);
        self.update_submenu();
        self.submenu.popup(None, None, gtk.status_icon_position_menu,
                           1, 0, self.status_icon
        );
        return;
    #do_list


    def do_connect(self, widget, argument):
        '''Connect to a location.'''
        command_line = [_EXPRESSVPN, 'connect'];
        if argument is not None:
            command_line.append(argument);
        #if
        retcode, stdout, stderr = call(*command_line);
        if retcode != 0:
            message = gtk.MessageDialog(
                parent=None,
                flags=0,
                type=gtk.MESSAGE_ERROR,
                buttons=gtk.BUTTONS_CLOSE,
                message_format=(
                    "'expressvpn connect %s' failed:\n%s" % (argument, err)
                )
            );
            message.run();
            message.destroy();
        else:
            self.update_all();
        #else
        return;
    #do_connect


    def do_disconnect(self, widget):
        '''Disconnect and update status.'''
        retcode, stdout, stderr = call(_EXPRESSVPN, 'disconnect');
        if retcode == 0:
            self.update_all();
        #if
        return;
    #do_disconnect

    ### painting functions ########################################

    def pic_label_box(self, image, text):
        '''Returns an hbox containing the given image and text.'''
        box = gtk.HBox(False, 13);
        im = gtk.Image();
        im.set_from_stock(image, gtk.ICON_SIZE_MENU);
        box.pack_start(im, False);
        box.pack_start(gtk.Label(text), False);
        box.show_all();
        return box;
    #pic_label_box


    def update_icon(self):
        '''Update the system tray icon.'''
        if self.status == None:
            self.status_icon.set_from_stock(gtk.STOCK_DISCONNECT);
            self.status_icon.set_tooltip("disconnected");
        else:
            self.status_icon.set_from_stock(gtk.STOCK_CONNECT);
            self.status_icon.set_tooltip(self.status);
        #else
        self.status_icon.set_visible(True);
        return;
    #update_icon


    def show_menu(self, widget, event):
        '''Pops open the main menu.'''
        self.menu.popup(None, None, gtk.status_icon_position_menu,
                        event.button, event.time, self.status_icon
        );
        return;
    #show_menu


    def show_about(self, widget):
        '''Open an info window.'''
        about_window = gtk.Window(gtk.WINDOW_TOPLEVEL);
        about_window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DIALOG);
        about_window.set_resizable(False);
        about_window.set_deletable(False);
        about_window.set_border_width(11);
        about_window.set_position(gtk.WIN_POS_CENTER_ALWAYS);
        about_window.set_title('About czexpressvpn');
        about_box = gtk.VBox(False, 0);
        about_window.add(about_box);
        about_contents = gtk.Label();
        about_contents.set_markup(
            '''<span face="monospace"><b>czexpressvpn - graphical interface for ExpressVPN</b>

<i>Copyright 2017 Alexander Czutro</i>

This program is free software: you can redistribute it or modify it
under the terms  of the GNU General Public License  as published by
the Free Software  Foundation, either version 3 of  the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT  ANY  WARRANTY;  without   even  the  implied  warranty  of
MERCHANTABILITY or FITNESS  FOR A PARTICULAR PURPOSE.   See the GNU
General Public License for more details.

You should have  received a copy of the GNU  General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.</span>
'''
        );
        about_box.pack_start(about_contents);
        about_ok = gtk.Button("_OK");
        about_box.pack_start(about_ok);
        about_ok.connect_object("clicked", gtk.Widget.destroy, about_window);
        about_window.show_all();
    #show_about


    def update_menu(self):
        '''Updates the contents of the main menu.'''
        self.menu = gtk.Menu();

        menu_item = gtk.MenuItem();
        menu_item.add(self.pic_label_box(gtk.STOCK_ABOUT, "about"));
        menu_item.connect('activate', self.show_about);
        self.menu.append(menu_item);

        self.menu.append(gtk.SeparatorMenuItem());

        menu_item = gtk.MenuItem();
        if self.status is None:
            menu_item.add(
                self.pic_label_box(gtk.STOCK_NO, "disconnected")
            );
        else:
            menu_item.add(self.pic_label_box(gtk.STOCK_YES, self.status));
        #else
        menu_item.connect('activate', self.update_all, None);
        self.menu.append(menu_item);

        self.menu.append(gtk.SeparatorMenuItem());

        if self.status is None:
            self.get_locations('recent');

            if len(self.locations) == 0:
                menu_item = gtk.MenuItem();
                menu_item.add(
                    self.pic_label_box(gtk.STOCK_CONNECT,
                                       'reconnect to last location')
                );
                menu_item.connect('activate', self.do_connect, None);
                self.menu.append(menu_item);
            #if

            for code, label in self.locations:
                menu_item = gtk.MenuItem();
                menu_item.add(self.pic_label_box(gtk.STOCK_CONNECT,
                                                 'connect to ' + label)
                );
                menu_item.connect('activate', self.do_connect, code);
                self.menu.append(menu_item);
            #for

            menu_item = gtk.MenuItem();
            menu_item.add(self.pic_label_box(gtk.STOCK_INDEX,
                                             'recommended locations')
            );
            menu_item.connect('activate', self.do_list, 'recommended');
            self.menu.append(menu_item);

            menu_item = gtk.MenuItem();
            menu_item.add(self.pic_label_box(gtk.STOCK_INDEX,
                                             'all locations')
            );
            menu_item.connect('activate', self.do_list, None);
            self.menu.append(menu_item);
        else:
            menu_item = gtk.MenuItem();
            menu_item.add(self.pic_label_box(gtk.STOCK_DISCONNECT,
                                             'disconnect')
            );
            menu_item.connect('activate', self.do_disconnect);
            self.menu.append(menu_item);
        #else

        self.menu.append(gtk.SeparatorMenuItem());

        menu_item = gtk.MenuItem();
        menu_item.add(self.pic_label_box(gtk.STOCK_QUIT, 'exit'));
        menu_item.connect('activate', self.do_exit);
        self.menu.append(menu_item);

        self.menu.show_all();
        return;
    #update_menu


    def update_submenu(self):
        '''Updates the sub-menu that contains the connection locations.'''
        self.submenu = gtk.Menu();
        for code, label in self.locations:
            self.menu_item = gtk.MenuItem();
            self.menu_item.add(self.pic_label_box(gtk.STOCK_CONNECT,
                                                  'connect to ' + label)
            );
            self.menu_item.connect('activate', self.do_connect, code);
            self.submenu.append(self.menu_item);
        #for
        self.submenu.show_all();
        return;
    #update_submenu


    def update_all(self, arg1=None, arg2=None):
        '''Updates all internal objects and the internal status.'''
        #gobject.source_remove(self.cursleep);
        self.get_status();
        self.update_icon();
        self.update_menu();
        #self.cursleep = gobject.timeout_add_seconds(60, self.forever_loop);
        return;
    #update_all


    def do_exit(self, widget=None):
        '''Quits the application.'''
        gobject.source_remove(self.cursleep);
        gtk.main_quit();
        return;
    #do_exit


    def forever_loop(self):
        '''Tasks that need to be repeated regularly.'''
        self.update_all();
        # function will continue to be called regularly while it
        # returns True
        return True;
    #forever_loop

#Trayhub


### main ######################################################################

if __name__ == '__main__':
    tray = Trayhub();
    gtk.main();
    exit(0);
#if

### end ########################################################### aczutro ###
